namespace RegulusLibrary.Services.Sources.DataStructures;

public record OldDbBirdRecord
{
    public int IDR_Podab { get; set; }
    public int? IdrZesz { get; set; }
    public int? IdBase { get; set; }
    public int? IdInp { get; set; }
    public string? Sta { get; set; }
    public int? Row { get; set; }
    public string? ST { get; set; }
    public string? CoStaSit { get; set; }
    public int? Year { get; set; }
    public string? Seas { get; set; }
    public DateTime? Date { get; set; }
    public int? Hour { get; set; }
    public string? Ring { get; set; }
    public string? Status { get; set; }
    public string? Spec { get; set; }
    public string? Sex { get; set; }
    public string? Age { get; set; }
    public string? Ringer { get; set; }
    public float? Mass { get; set; }
    public float? Fat { get; set; }
    public float? Wing { get; set; }
    public float? Tail { get; set; }
    public float? D2 { get; set; }
    public float? D3 { get; set; }
    public float? D4 { get; set; }
    public float? D5 { get; set; }
    public float? D6 { get; set; }
    public float? D7 { get; set; }
    public float? D8 { get; set; }
    public string? PP { get; set; }
    public string? P1 { get; set; }
    public string? P2 { get; set; }
    public string? P3 { get; set; }
    public string? P4 { get; set; }
    public string? P5 { get; set; }
    public string? P6 { get; set; }
    public string? Notes { get; set; }
    public int? OK { get; set; }
    public DateTime? TS_Import { get; set; }
    public DateTime? TS_Zesz { get; set; }
    public bool? Sel { get; set; }
    public int? MD { get; set; }
    public string? RNG { get; set; }
    public string? AgeT { get; set; }
    public DateTime? DT { get; set; }
    public string? Ztyp { get; set; }
    public int? Znr { get; set; }
    public double? P1PC { get; set; }
    public double? P2PC { get; set; }
    public double? P1P2 { get; set; }
    public double? Kipp { get; set; }
    public string? Tarsus { get; set; }
    public double? THL { get; set; }
    public string? Bill1 { get; set; }
    public double? Bill2 { get; set; }
    public double? Claw { get; set; }
    public double? Emarg { get; set; }
    public string? Notch_mm { get; set; }
    public double? Notch_tip { get; set; }
    public string? Moult_short { get; set; }
    public string? Parasite { get; set; }
    public int? N_unmoult_cov { get; set; }
    public double? X1 { get; set; }
    public double? X2 { get; set; }
    public double? X3 { get; set; }
    public double? X4 { get; set; }
    public double? X5 { get; set; }
    public double? X6 { get; set; }
    public string? Net { get; set; }
}