//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegulusTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegulusTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] access_example {
            get {
                object obj = ResourceManager.GetObject("access_example", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR_Podab,IdBaza,IdSezon,IdZesz,Ztyp,Znr,Zpage,Zrow,CoStaSit,Year,Seas,Date,Pole13,Date2,MD,Hour,Pole17,Ring Type,Ring Ser,Ring No,Ring,Pole22,Stat,Net,Species Code,English Name,Latin Name,AddInfo,Sex,Pole30,&apos;?&apos;,Euring,Age,Pole34,Pole35,WIEK,SZATA,Fat,Pole39,Tip,Pole41,M1,Pole43,M2,Pole45,M3,Pole47,M4,Pole49,M5,Pole51,M6,Pole53,D2,Pole55,D3,Pole57,D4,Pole59,D5,Pole61,D6,Pole63,D7,Pole65,D8,Pole67,Extra 1,Pole69,Extra 2,Pole71,Wing,Pole73,Tail,Pole75,Weight,Pole77,DW,Notch/Dziób,Pole80,LocN/Pazur/Kipp,Pole82 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csv_example {
            get {
                return ResourceManager.GetString("csv_example", resourceCulture);
            }
        }
    }
}
